broadinstitute/barclay

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/argparser/CommandLineException.java
src/main/java/org/broadinstitute/barclay/argparser/LegacyCommandLineArgumentParser.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java
src/test/java/org/broadinstitute/barclay/argparser/LegacyCommandLineArgumentParserTest.java

* Handling max/min values in `CommandLineArgumentParser` (solves partially #6)
* New `CommandLineArgumentException` for out-of-range values.
* `LegacyCommandLineArgumentParser` does not have max/min validation: Picard is not supporting currently this feature in its parser.
* Recommended boundaries are not handled yet.

Handling max/min values in CommandLineArgumentParser

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineException.java

and change their base class to RuntimeException so that all CommandLineExceptions can be treated as user errors.

Change internal command line exception classes to package-protected RuntimeExceptions

---

src/main/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandler.java
src/test/java/org/broadinstitute/barclay/help/DocumentationGenerationIntegrationTest.java
src/test/java/org/broadinstitute/barclay/help/TestArgumentContainer.java
src/test/resources/org/broadinstitute/barclay/help/expected/org_broadinstitute_barclay_help_TestArgumentContainer.html
src/test/resources/org/broadinstitute/barclay/help/expected/org_broadinstitute_barclay_help_TestArgumentContainer.html.json

The current doc output contains no argument name if the Argument annotation doesn't specify one, but it should use the field name.
Also fixes the test for JSON doc output, which was redundantly checking the html output file instead of the JSON output file.

Use field name in doc when annotation has no arg name.

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java

- Fixes #40 
- Add previously failing test

Fix unbounded null throwing exception

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/argparser/LegacyCommandLineArgumentParser.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java
src/test/java/org/broadinstitute/barclay/argparser/TaggedArgumentTest.java

Currently when we generate a command line for display purposes, it contains the fully qualified name of the tool/class ("org.broadinstitute.hellbender.tools.PrintReads"). Propose to change it to use the simple name ("PrintReads").

Use the simple (unqualified) tool name when displaying a command line.

---

src/main/java/org/broadinstitute/barclay/help/HelpDoclet.java

Includes the following changes:
- Make public some getters and implement new ones. This will be helpful for DocWorkUnitHandler implementations.
- Use getters within the class to use overriden ones from sub-classes.
- New option and field (including getter) for different index extension, which default outputFileExtension.
Close #59

Index output extension option

---

src/main/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandler.java
src/test/java/org/broadinstitute/barclay/argparser/TestProgramGroup.java
src/test/java/org/broadinstitute/barclay/help/TestExtraDocs.java
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/index.html
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/org_broadinstitute_barclay_help_TestExtraDocs.html
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/org_broadinstitute_barclay_help_TestExtraDocs.html.json
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/index.html
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/org_broadinstitute_barclay_help_TestExtraDocs.html
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/org_broadinstitute_barclay_help_TestExtraDocs.html.json

Fixes https://github.com/broadinstitute/barclay/issues/63 and https://github.com/broadinstitute/barclay/issues/62 (originally discovered as https://github.com/broadinstitute/gatk-protected/issues/1048). Also removes the ridiculous test case that has an "extraDocs" reference to itself.

Don't require no-arg constructors for DocumentedFeatures.

---

src/main/java/org/broadinstitute/barclay/help/HelpDoclet.java

Very simple patch to allow integrating custom options for a doclet. Currently parsing custom options is a bit painful, but after this change it is as simple as: 
```java
public class CustomDoclet extends HelpDoclet {
....
private static final String DEPENDENCY_VERSION_OPTION = "-dependency-version";
protected static Map<String, String> dependencyVersions = new LinkedHashMap<>();
@Override
protected parseOption(Option[] options) {
super.parseOption(options);
if (options[0].equals(DEPENDENCY_VERSION_OPTION))
dependencyVersions.put(options[1], options[2]);
}
public static int optionLength(final String option) {
if (option.equals(DEPENDENCY_VERSION_OPTION)) return 3;
return HelpDoclet.optionLength(option);
}
....
}
```

Extract method to allow custom doclet options

---

src/main/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandler.java
src/main/java/org/broadinstitute/barclay/help/HelpDoclet.java
src/main/resources/org/broadinstitute/barclay/helpTemplates/generic.template.html
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/org_broadinstitute_barclay_help_TestArgumentContainer.html
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/org_broadinstitute_barclay_help_TestArgumentContainer.json
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/org_broadinstitute_barclay_help_TestArgumentContainer.html
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/org_broadinstitute_barclay_help_TestArgumentContainer.json
src/test/resources/org/broadinstitute/barclay/help/templates/TestDoclet/generic.template.html

Pulled out some small changes in a larger  PR ( #82 )  into this one for ease of merging.
Added minElements and maxElements to freemarker objects (they were
present in the data, but not being pushed into freemarker).
Fixed display names not to show up with '-' as values when they are
empty or null.
ProcessIndexTemplate is now protected.
In the default templates, arguments that have no synonyms no longer
render synonyms at all (as opposed to showing up as NA).

Several small bugfixes and updates.

---

src/main/java/org/broadinstitute/barclay/help/HelpDoclet.java

Fixes an issue when creating a tab-completion file and using the default templates.
Before the code was erroneously trying to read a file for the template whether or not the user specified using the default template.  This caused a FileNotFoundException when that path did not exist even when using the default template.
Now the code correctly splits creating the template object into two cases - the default template and a user-defined template.

Fixed a bug in pulling templates from the classpath.

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java

Currently, a missing argument results in this output:
> A USER ERROR has occurred: Argument output was missing: Argument 'output' is required. are specified.
Note the dangling "are specified." at the end.

Fix bad command line output error message formatting.

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/argparser/LegacyCommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/utils/Utils.java
src/test/java/org/broadinstitute/barclay/utils/UtilsUnitTest.java

The wordWrap functionality used here is designed to wrap a single line, but was used on a paragraphs. this leads to poor-looking descriptions of the arguments in the help-docs. 
This PR fixes that.

Fix word wrapping in the argument description. 

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/test/java/org/broadinstitute/barclay/argparser/CollectionArgumentUnitTests.java

Change the default extension for auto-expansion of command line args to ".args" from ".list", which was causing problems with Picard interval lists. Fixes https://github.com/broadinstitute/barclay/issues/94.
This is a short term fix. The longer term fix is in https://github.com/broadinstitute/barclay/pull/95.

Change the default args list expansion extension to .args.

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/argparser/LegacyCommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/utils/Utils.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java
src/test/java/org/broadinstitute/barclay/argparser/LegacyCommandLineArgumentParserTest.java

- fixes #103
- also adds some finals and other aesthetics

Wraps text in preamble as well

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/argparser/CommandLinePluginDescriptor.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLinePluginUnitTest.java

I accomplished this by making the PluginDescriptor responsible for knowing which arguments belong to it and passing every argument to the descriptor. 
Fixes #121

Changed argument parser to handle argument collections on PluginDescriptors

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/argparser/ExperimentalFeature.java
src/main/java/org/broadinstitute/barclay/argparser/LegacyCommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandler.java
src/main/java/org/broadinstitute/barclay/help/DocWorkUnit.java
src/main/java/org/broadinstitute/barclay/help/GSONWorkUnit.java
src/main/java/org/broadinstitute/barclay/help/HelpDoclet.java
src/main/resources/org/broadinstitute/barclay/helpTemplates/generic.html.ftl
src/main/resources/org/broadinstitute/barclay/helpTemplates/generic.index.html.ftl
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java
src/test/java/org/broadinstitute/barclay/argparser/LegacyCommandLineArgumentParserTest.java
src/test/java/org/broadinstitute/barclay/help/DocWorkUnitTest.java
src/test/java/org/broadinstitute/barclay/help/testinputs/TestExtraDocs.java
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/index.html
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/org_broadinstitute_barclay_help_testinputs_TestArgumentContainer.json
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/org_broadinstitute_barclay_help_testinputs_TestExtraDocs.html
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/org_broadinstitute_barclay_help_testinputs_TestExtraDocs.json
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/index.html
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/org_broadinstitute_barclay_help_testinputs_TestArgumentContainer.html
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/org_broadinstitute_barclay_help_testinputs_TestArgumentContainer.json
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/org_broadinstitute_barclay_help_testinputs_TestExtraDocs.html
src/test/resources/org/broadinstitute/barclay/help/expected/TestDoclet/org_broadinstitute_barclay_help_testinputs_TestExtraDocs.json
src/test/resources/org/broadinstitute/barclay/help/templates/TestDoclet/generic.html.ftl
src/test/resources/org/broadinstitute/barclay/help/templates/TestDoclet/generic.index.html.ftl

This adds the `@Experimental` annotation (mutually exclusive with` @Beta`). It also fixes a couple of other bugs (we weren't adding the beta property to the json output, and some of the test templates weren't respecting the data type of the freemark map entries; more incentive to develop the unit testing framework once we can get to it).

Add @Experimental annotation, test fixes.

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/argparser/CommandLinePluginDescriptor.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLinePluginUnitTest.java

DO NOT MERGE.
@magicDGS Please take a look at the changes to the descriptor interface in this branch. I've changed some names, as well as some method contract descriptions.
If the read filter plugin implemented this interface, and you had the ability inject argument definitions as you do in https://github.com/broadinstitute/gatk/pull/2355, would that be sufficient to enable your filter plugin use cases using just method overrides ?
Summary of the main changes I made:
- getAllInstances -> getResolvedInstances (changed contract to return all “resolved” instances, including defaults, and note that resulting list may be different if called pre/post parseArgs)
- getDefaultInstances -> getDefaultInstances (changed contract to say the resulting list may be different if called pre/post parseArgs) …

Updates to CommandLinePluginDescriptor interface.

---

src/main/java/org/broadinstitute/barclay/argparser/Argument.java
src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/test/java/org/broadinstitute/barclay/argparser/CollectionArgumentUnitTests.java

accept .list in addition to .args as a file expansion extension, and handle display representation of long command lines.

Add suppressFileExpansion property to @Argument.

---

src/main/java/org/broadinstitute/barclay/argparser/CommandLineException.java

Discovered while working on wdl gen. The order of the arguments was reversed.

*Fix message construction logic for out-of-range error.

---

src/main/java/org/broadinstitute/barclay/help/BashTabCompletionDocWorkUnitHandler.java
src/main/java/org/broadinstitute/barclay/help/BashTabCompletionDoclet.java
src/main/java/org/broadinstitute/barclay/help/HelpDoclet.java
src/test/resources/org/broadinstitute/barclay/help/expected/BashTabCompletionDoclet/bashTabCompletionDocletTestLaunch-completion.sh
src/test/resources/org/broadinstitute/barclay/help/expected/BashTabCompletionDoclet/bashTabCompletionDocletTestLaunchWithDefaults-completion.sh

This adds a filter to the tab completion doclet so it will only select command line programs. It also adds a custom work unit handler for tab completion in order to suppress resolution of extra docs, since the command line program filtering can result in dangling extra docs references (which is ok for tab completion, since extraDocs references are relevant only for documentation).
Note that the tab completion test results changed; the test container we use for all the integration tests contains an "extraDocs" reference to a component named `TestExtraDocs` that is not a command line program. This was previously being included in the the output shell script, but now no longer is.
Fixes https://github.com/broadinstitute/barclay/issues/109 (and …

Filter non-CLPs from inclusion in tab completion.

---

src/main/java/joptsimple/BarclayOptionParser.java
src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java

I don't see any sanctioned way to do this; the code in this PR works by inserting a class into the jopt package namespace to allow a custom subclass of the parser.

*Disable jopt argument clustering.

---

src/test/resources/org/broadinstitute/barclay/help/expected/WDLDoclet/org_broadinstitute_barclay_help_testinputs_TestArgumentContainer.wdl

The previous branch (https://github.com/broadinstitute/barclay/pull/165, with WDL updates) added a new test, but the test output for that new test has to be updated to reflect the changes that were made to the input files in the last branch (https://github.com/broadinstitute/barclay/pull/160) so the tests on master will pass. (All of the WDL/Doc/Tab generation tests share the same test inputs - when changing a test input, often all of the test outputs need to be updated).

Update test output for a test that was added in the previous branch that was merged.

---

src/main/java/org/broadinstitute/barclay/argparser/NamedArgumentDefinition.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java

The command line help for the Barclay parser uses a hybrid display format left over from the legacy parser (`--input:GATKPath`), which is confusing when Barclay parser syntax is being used. This changes the display syntax for the Barclay parser to use `--input <GATKPath>`, i.e.:
```
Required Arguments:
--input,-I <GATKPath>         BAM/SAM/CRAM file containing reads  This argument must be specified at least once.
Required. 
--output,-O <GATKPath>        Write output to this file  Required. 
...
```
See GATK https://github.com/broadinstitute/gatk/issues/6775.

Fix command line data type display to not use an embedded colon.

---

src/main/java/org/broadinstitute/barclay/help/BashTabCompletionDoclet.java
src/main/java/org/broadinstitute/barclay/help/DocWorkUnitHandler.java
src/main/java/org/broadinstitute/barclay/help/HelpDoclet.java

Make some static `HelpDoclet` members that were mutable into instance variables to prevent residual side effects from causing random test failures when tests are run serially.

Fix mutable HelpDoclet member declarations.

---

src/main/java/org/broadinstitute/barclay/argparser/NamedArgumentDefinition.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java

* When writing the help output don't output the argument in both short and long form if
the shortname is the same as the long name.
i.e.  --argument, -argument -> --argument

Deduplicate argument names in help when fullname = shortname

---

README.md
build.gradle

Fixes the pom so Sonatype will not reject Barclay because there are missing attributes. Also update the readme with the new dependencies.

Fix pom attributes, update readme to reflect new dependencies.

---

src/main/java/org/broadinstitute/barclay/argparser/ClassFinder.java

@cmnbroad I stumbled on this randomly and figured we should close it.
* Adds a try-with-resources block to close a zipfile in the class finder
* And the impossible to resist first java 17 related minor refactoring.

Fix file leak in ClassFinder

---

src/main/resources/org/broadinstitute/barclay/helpTemplates/generic.html.ftl
src/test/resources/org/broadinstitute/barclay/help/expected/HelpDoclet/org_broadinstitute_barclay_help_testinputs_TestArgumentContainer.html

This template is only used for testing Barclay, but its still wrong.

Fix reversed logic in the help template.

---

build.gradle
src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/argparser/CommandLineParser.java
src/main/java/org/broadinstitute/barclay/argparser/LegacyCommandLineArgumentParser.java
src/main/java/org/broadinstitute/barclay/argparser/NamedArgumentDefinition.java
src/main/java/org/broadinstitute/barclay/argparser/TaggedArgumentParser.java
src/main/java/org/broadinstitute/barclay/help/DefaultDocWorkUnitHandler.java
src/main/java/org/broadinstitute/barclay/help/WDLTransforms.java
src/main/java/org/broadinstitute/barclay/help/WDLWorkUnitHandler.java
src/main/java/org/broadinstitute/barclay/utils/Pair.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java

* updating vulnerable dependencies
* replacing use of commons-lang Path with new barclay Path
* reducing dependency scope where possible

Replacing the gradle java plugin with java-library

---

src/main/java/org/broadinstitute/barclay/help/scanners/UnknownInlineTagScanner.java

This *seems* to fix a bug in picard when running picard docs with java 21.  The docs pass and look reasonable with it instead of exploding with an NPE.
```
java.lang.NullPointerException: Cannot invoke "com.sun.source.doctree.DocTree.getKind()" because "t" is null
at org.broadinstitute.barclay.help.scanners.UnknownInlineTagScanner.scan(UnknownInlineTagScanner.java:44)
at org.broadinstitute.barclay.help.scanners.UnknownInlineTagScanner.scan(UnknownInlineTagScanner.java:18)
at jdk.compiler/com.sun.source.util.DocTreeScanner.visitValue(DocTreeScanner.java:680)
at jdk.compiler/com.sun.tools.javac.tree.DCTree$DCValue.accept(DCTree.java:1402)
at jdk.compiler/com.sun.source.util.DocTreeScanner.scan(DocTreeScanner.java:90)
at org.broadinstitute.barclay.help.scanners.UnknownInlineTagScanner.scan(Un …
```

adding a null check to avoid NPE in picard

---

.github/workflows/tests.yml
build.gradle
src/main/java/org/broadinstitute/barclay/argparser/ArgumentDefinition.java
src/main/java/org/broadinstitute/barclay/argparser/ClassFinder.java
src/main/java/org/broadinstitute/barclay/argparser/NamedArgumentDefinition.java
src/main/java/org/broadinstitute/barclay/argparser/PositionalArgumentDefinition.java
src/main/java/org/broadinstitute/barclay/help/DocWorkUnit.java

- Updating to java 21
- update github actions to use java 21

lb update to 21

---

src/main/java/org/broadinstitute/barclay/argparser/SpecialArgumentsCollection.java
src/test/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParserTest.java

@droazen @cmnbroad Making the special arguments consistent but leaving the old way for now.

Adding new style versions to special arguments

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

@cmnbroad Gradle is removing the magic syntax `properyName value`.  Apparently that's a gradle specific thing and not groovy.  
Currently you can set a property with any of these mechanisms:
propertyName = value
setPropertyName(value)
setPropertyName value
propertyName(value)
propertyName value
But now it will just be these which are the standard groovy options, either implicitly call the setter using the standard setter, or call the setter explicitly.  
propertyName = value
setPropertyName(value)
setPropertyName value
This has confused the hell out of me for years, so good riddance!

Update gradle to 8.12
